const products = [{
    id:1,
    img:"./img/product01.png",
    price:2400,
    name:"Laptop",
    description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, error.",
},
{
    id:2,
    img:"./img/product02.png",
    price:3400,
    name:"Head Phone",
    description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, error.",
},
{
    id:3,
    img:"./img/product03.png",
    price:1400,
    name:"Mac Book",
    description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, error.",
},
{
    id:4,
    img:"./img/product04.png",
    price:400,
    name:"Samsung Tab",
    description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, error.",
},
{
    id:5,
    img:"./img/product05.png",
    price:6700,
    name:"Headphones",
    description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, error.",
},
{
    id:6,
    img:"./img/product06.png",
    price:3400,
    name:"Laptop",
    description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, error.",
},
{
    id:7,
    img:"./img/product07.png",
    price:3400,
    name:"Samsung M32",
    description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, error.",
},
{
    id:8,
    img:"./img/product08.png",
    price:7800,
    name:"Lenovo Yoga",
    description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, error.",
},
{
    id:9,
    img:"./img/product09.png",
    price:1800,
    name:"Nikon Camera",
    description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, error.",
},
{
    id:10,
    img:"./img/shop01.png",
    price:7800,
    name:"Laptop",
    description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, error.",
},
{
    id:11,
    img:"./img/shop02.png",
    price:600,
    name:"Sony Camera",
    description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, error.",
},
{
    id:12,
    img:"./img/shop03.png",
    price:7800,
    name:"Head Phone",
    description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, error.",
},

];